create policy "Users can read own profile"
create policy "Superadmins can read all profiles"
create policy "Users can read own chat threads"
create policy "Users can create own chat threads"
create policy "Users can update own chat threads"
create policy "Users can read own chat messages"
create policy "Users can create own chat messages"
create policy "Users can read own notes"
create policy "Users can insert own notes"
create policy "Users can update own notes"
create policy "Users can delete own notes"
create policy "Users can read own calendar events"
create policy "Users can insert own calendar events"
create policy "Users can update own calendar events"
create policy "Users can delete own calendar events"
create policy "Users can read own notes"
create policy "Users can insert own notes"
create policy "Users can update own notes"
create policy "Users can delete own notes"
create policy "Users can read own calendar events"
create policy "Users can insert own calendar events"
create policy "Users can update own calendar events"
create policy "Users can delete own calendar events"
create policy "Authenticated users can read enabled chat models"
create policy "Superadmins can read all chat models"
create policy "Superadmins can update chat models"
create policy "Auth admin can read profiles for auth hooks"
create policy "Users can update own assistant chat messages"
create policy "Users can read own chat thread files"
create policy "Users can view own chat storage files"
create policy "Users can upload own chat storage files"
create policy "Users can update own chat storage files"
create policy "Users can delete own chat storage files"
